### ISSUE TITLE
Lambda now supports nodejs14.x - update typedefs to accommodate

### ISSUE THREAD

**Issue by rcoundon** [serverless/typescript#22]
I've submitted a  PR https://github.com/serverless/typescript/pull/21

**Comment by fredericbarthelet** [comment]
Hi @rcoundon and thanks for submitting a PR :)
This repository aims to dynamically generates typescript definitions using the JSON schema generated in https://github.com/serverless/serverless. No modification shall be done directly to `index.d.ts` as those will be erased once a new Serverlesss framework version is released.

In order to make your modification, you should add the new nodejs layer directly within serverless/serverless in https://github.com/serverless/serverless/blob/7c998e03ca104948c6c2673c9fee6992689219df/lib/plugins/aws/provider.js#L452

Once your PR on serverless merged and new version of the framework published, this repository will automatically update its Typescript definition to reflect this change :)

**Comment by rcoundon** [comment]
Ah, I see. Thanks @fredericbarthelet
