### ISSUE TITLE
httpApi event annotation is mistaken.

### ISSUE THREAD

**Issue by omer-to** [serverless/typescript#33]
Starting at line 972, this is the definition for `httpApi`.

So `httpApi` is either a string or an object. And if It is object, the `method` property is annotated as `optional`, however, that is not the case, and will result in deployment failure.

```typescript
httpApi:
              | string
              | {
                  authorizer?:
                    | string
                    | (
                        | {
                            [k: string]: unknown;
                          }
                        | {
                            [k: string]: unknown;
                          }
                      );
                  method?: string;
                  path: string;
                };
```

Moreover, there are other optional properties that would prevent from typescript compilation (the project was created with was-nodejs-typescript).
The example is `cors`. Here is how it behaves when I try to set `cors`:

![cors error](https://user-images.githubusercontent.com/63205993/110674063-922dd000-81e2-11eb-9b0b-0e0bc3abb21b.png)

**Comment by fredericbarthelet** [comment]
Hi @omer-to and thanks for submitting this issue.

There is one case in which only path is required: when `path` equals `'*'` -> see https://github.com/serverless/serverless/blob/aa7b66a66c199c236bedfbc3b3aab39acb0eb6ad/lib/plugins/aws/package/compile/events/httpApi.js#L372-L380

@medikoo @pgrzesik shouldn't we deprecate this single usage in order to simplify the httpApi configuration with 2 cases : either a string containing the regex for method and path (and the '*' use case); or an object with both method and path as required params ?

--- 

As for the `cors` option, the correct location for this parameter is `provider.httpApi.cors`, not `functions.{myFunction}.events[0].httpApi.cors` -> see documentation in https://www.serverless.com/framework/docs/providers/aws/events/http-api#cors-setup

**Comment by medikoo** [comment]
> @medikoo @pgrzesik shouldn't we deprecate this single usage in order to simplify the httpApi configuration with 2 cases : either a string containing the regex for method and path (and the '*' use case); or an object with both method and path as required params ?

@fredericbarthelet I understand it's about deprecating `{ path: "*" }` in favor of `{ path: "*", method: "*" }`. It could make sense, if also specific method could be assigned for `path: *`, but thing is that for `path: *` there only valid value is `method: *`, and that would make this additional configuration line unnecessarily verbose.

**Comment by fredericbarthelet** [comment]
@medikoo my intend was to deprecate `{ httpApi: { path: "*" } }` in favor of `{ httpApi: "*" }`. WDYT ?

**Comment by medikoo** [comment]
> my intend was to deprecate { httpApi: { path: "*" } } in favor of { httpApi: "*" }. WDYT ?

I think any shorthand notation should have representation in object notation, and following that will break that rule.

**Comment by fredericbarthelet** [comment]
Understood :) So we keep it that way. Thanks @medikoo 

@omer-to is everything clearer regarding your comments or do you still need some help ?

**Comment by fredericbarthelet** [comment]
Hi @omer-to, I'm closing this issue. Feel free to re-open in case you face additional problems :)
